#!/usr/bin/env python3
"""
Offline accuracy evaluation (pandas) — the numbers for the SIH report.

Runs the REAL pipeline (main.process_record) over the synthetic corpus from
scripts/train_format_gate.py with no LLM keys configured (discovery degrades
to heuristics, exactly as in the no-key deployment), then builds:

  1. per-family breakdown: line counts, processing modes, mean/p50 latency,
     gate family-guess precision on known families
  2. novel-format detection: gate precision/recall on NEVER-SEEN families
  3. tier effectiveness: how many lines resolved by each tier (i.e. how often
     an LLM would have been needed without the Drain3 rule map)

Writes docs/accuracy_report.md and prints the same tables to stdout.

Usage:  pip install -r requirements-analysis.txt
        python scripts/evaluate_accuracy.py [--n-per-family 250] [--seed 7]
"""
from __future__ import annotations

import argparse
import os
import random
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

# No LLM configuration: discovery runs heuristics, no network is touched.
for k in ("GEMINI_API_KEY", "GOOGLE_API_KEY", "GROQ_API_KEY", "ANTHROPIC_API_KEY"):
    os.environ.pop(k, None)

import pandas as pd  # noqa: E402

import main as server  # noqa: E402
from pipeline.format_gate import GATE, FormatGate  # noqa: E402
from pipeline.template_miner import mask_line  # noqa: E402
from train_format_gate import GENS, UNKNOWN, make_corpus  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--n-per-family", type=int, default=250)
    ap.add_argument("--unknown-per-family", type=int, default=60)
    ap.add_argument("--seed", type=int, default=7)
    args = ap.parse_args()

    # A FRESH gate instance scoring the masked lines gives us precision of the
    # family classifier independently of the server's singleton state.
    gate_clf = FormatGate()
    if not gate_clf.loaded:
        print("ERROR: models/format_gate.pkl missing — run scripts/train_format_gate.py first")
        return 1

    random.seed(args.seed)
    server.template_tier.reset()

    # --------------------- 1) process the known corpus ----------------------
    X, y = make_corpus(args.n_per_family, GENS)
    t0 = time.perf_counter()
    results = [server.process_record(l) for l in X]
    server_s = time.perf_counter() - t0
    # gate-only metrics do not depend on which tier answered the line; score
    # every masked line directly so classification/novelty rates are honest.
    t0 = time.perf_counter()
    gate_rows = [gate_clf.inspect(mask_line(l)) for l in X]
    gateeval_s = time.perf_counter() - t0
    total_s = server_s
    df = pd.DataFrame({
        "family": y,
        "mode": [r["mode"] for r in results],
        "latency_ms": [r["latency_ms"] for r in results],
        "gate_novel": [g["novel"] for g in gate_rows],
        "gate_family": [g["family_guess"] for g in gate_rows],
        "signature": [r["format"] for r in results],
    })
    fam_acc = (df["gate_family"] == df["family"]).mean()

    modes = df.groupby(["family", "mode"]).size().unstack(fill_value=0)
    summary = df.groupby("family").agg(
        lines=("family", "size"),
        mean_ms=("latency_ms", "mean"),
        p50_ms=("latency_ms", "median"),
        novel_rate=("gate_novel", "mean"),
        fam_acc=("gate_family", lambda s: (s == df.loc[s.index, "family"]).mean()),
    ).round(4)
    out = summary.join(modes).fillna(0).astype({"lines": int})

    # --------------------- 2) never-seen families ---------------------------
    server.template_tier.reset()
    server.parser.cache.clear()
    Xu, yu = make_corpus(args.unknown_per_family, UNKNOWN)
    res_u = [server.process_record(l) for l in Xu]
    gate_rows_u = [gate_clf.inspect(mask_line(l)) for l in Xu]
    du = pd.DataFrame({
        "family": yu,
        "mode": [r["mode"] for r in res_u],
        "gate_novel": [g["novel"] for g in gate_rows_u],
        "signature": [r["format"] for r in res_u],
    })
    unknown_catch = du["gate_novel"].mean()
    per_unknown = du.groupby("family")["gate_novel"].mean().round(3)

    # Novelty precision on the mixed stream
    known_flag_rate = df["gate_novel"].mean()
    prec = (du["gate_novel"].sum() / (du["gate_novel"].sum() + df["gate_novel"].sum())) \
        if (du["gate_novel"].sum() + df["gate_novel"].sum()) else float("nan")

    # --------------------- 3) tier effectiveness ----------------------------
    tier_stats = dict(server.template_tier.stats)
    mode_share = (df["mode"].value_counts(normalize=True) * 100).round(2)

    tier = gate_clf.info
    lines = [
        "# Pipeline accuracy report (auto-generated by scripts/evaluate_accuracy.py)",
        "",
        f"- Corpus: {len(X)} lines / {df['family'].nunique()} known families (synthetic, every field varies)"
        f" + {len(Xu)} lines / {du['family'].nunique()} NEVER-SEEN families",
        f"- Server loop: {server_s:.1f} s → `{server_s/len(X)*1000:.2f} ms/line` mean"
        f" (heuristic discovery, no LLM key; the gate ran offline in this eval:"
        f" {gateeval_s/len(X)*1000:.2f} ms/line on all lines, in production it runs"
        f" ~{gateeval_s/max(1,len(X))*1000:.2f} ms only on the {mode_share.get('Discovery',0):.1f}% discovery lines)",
        f"- **Format-family classification (gate)**: {fam_acc*100:.2f}% over known families",
        f"- **Novel-format detection**: recall {unknown_catch*100:.1f}% on never-seen families"
        f" (per-family: {per_unknown.to_dict()}); precision {prec*100:.1f}%"
        f" (known-family false-alarm rate {known_flag_rate*100:.2f}%)",
        f"- **Processing-mode mix**: {mode_share.to_dict()} — lines on `Cached`/`Template-Rule` cost zero LLM calls;"
        f" only `{mode_share.get('Discovery', 0):.1f}%` of the stream touched the discovery engine",
        f"- Tier stats over the run: {tier_stats}",
        "",
        "## Per-family breakdown (known families)",
        "",
        out.to_markdown(),
        "",
        "## Novel templates (never-seen families)",
        "",
        per_unknown.round(3).to_frame("catch_rate").to_markdown(),
        "",
        f"_Gate artifact: {tier['n_train']} training masked-lines, threshold {tier['threshold']:.4f},"
        f" sklearn {tier.get('sklearn_version_expected')}, trained {tier['trained_at']}_",
    ]
    report_path = ROOT / "docs" / "accuracy_report.md"
    report_path.parent.mkdir(exist_ok=True)
    report_path.write_text("\n".join(lines))

    print("\n".join(lines[:11]))
    print("\n" + out.to_string())
    print(f"\n[+] report written to {report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
